from django import forms
from .models import TechnicalAnalysisHunter

class TechnicalAnalysisHunterForm(forms.ModelForm):
    class Meta:
        model = TechnicalAnalysisHunter
        fields = [
            'symbol', 
            'interval', 
            'lookback', 
            'comment', 
            'running', 
            'general_timeperiod',   
            'price_signals',
            'avg_close_period', 
            'trend_signals', 
            'adx_timeperiod', 
            'adx_strong_trend', 
            'adx_weak_trend', 
            'adx_no_trend', 
            'avg_adx_period', 
            'rsi_signals', 
            'rsi_divergence_signals', 
            'rsi_timeperiod',
            'rsi_buy', 
            'rsi_sell',
            'avg_rsi_period', 
            'vol_signals', 
            'avg_volume_period', 
            'macd_cross_signals', 
            'macd_histogram_signals', 
            'macd_timeperiod', 
            'macd_signalperiod', 
            'avg_macd_period',
            'bollinger_signals', 
            'bollinger_timeperiod', 
            'bollinger_nbdev', 
            'stoch_signals', 
            'stoch_divergence_signals', 
            'stoch_k_timeperiod', 
            'stoch_d_timeperiod',
            'stoch_buy', 
            'stoch_sell', 
            'avg_stoch_period', 
            'stoch_rsi_signals', 
            'stoch_rsi_timeperiod', 
            'stoch_rsi_k_timeperiod', 
            'stoch_rsi_d_timeperiod',
            'avg_stoch_rsi_period',  
            'ema_cross_signals',
            'ema_fast_signals', 
            'ema_slow_signals', 
            'ema_fast_timeperiod', 
            'ema_slow_timeperiod', 
            'avg_ema_period', 
            'di_signals', 
            'di_timeperiod',
            'avg_di_period', 
            'cci_signals', 
            'cci_divergence_signals', 
            'cci_timeperiod',
            'cci_buy', 
            'cci_sell', 
            'avg_cci_period', 
            'mfi_signals', 
            'mfi_divergence_signals', 
            'mfi_timeperiod',
            'mfi_buy', 
            'mfi_sell',
            'avg_mfi_period',
            'atr_signals',
            'atr_timeperiod',   
            'atr_buy_threshold',
            'avg_atr_period', 
            'vwap_signals', 
            'avg_vwap_period', 
            'psar_signals', 
            'psar_acceleration', 
            'psar_maximum',
            'avg_psar_period', 
            'ma50_signals', 
            'ma200_signals', 
            'ma_cross_signals',
        ]
        
    widgets = {
        'symbol': forms.TextInput(attrs={'class': 'form-control w-100'}),
        'interval': forms.TextInput(attrs={'class': 'form-control w-100'}),
        'lookback': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'comment': forms.Textarea(attrs={'class': 'form-control w-100', 'rows': 3}),
        'running': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'general_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'price_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'avg_close_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'trend_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'adx_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'adx_strong_trend': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'adx_weak_trend': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'adx_no_trend': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_adx_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'rsi_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'rsi_divergence_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'rsi_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'rsi_buy': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'rsi_sell': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_rsi_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'vol_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'avg_volume_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'macd_cross_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'macd_histogram_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'macd_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'macd_signalperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_macd_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'bollinger_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'bollinger_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'bollinger_nbdev': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'stoch_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'stoch_divergence_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'stoch_k_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'stoch_d_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'stoch_buy': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'stoch_sell': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_stoch_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'stoch_rsi_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'stoch_rsi_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'stoch_rsi_k_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'stoch_rsi_d_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_stoch_rsi_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'ema_cross_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'ema_fast_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'ema_slow_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'ema_fast_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'ema_slow_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_ema_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'di_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'di_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_di_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'cci_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'cci_divergence_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'cci_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'cci_buy': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'cci_sell': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_cci_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'mfi_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'mfi_divergence_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'mfi_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'mfi_buy': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'mfi_sell': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_mfi_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'atr_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'atr_timeperiod': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'atr_buy_threshold': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_atr_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'vwap_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'avg_vwap_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'psar_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'psar_acceleration': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'psar_maximum': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'avg_psar_period': forms.NumberInput(attrs={'class': 'form-control w-100'}),
        'ma50_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'ma200_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        'ma_cross_signals': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    }